- name: Copy ryslog configuration file
  ansible.builtin.template:
    src: ryslog.conf
    dest: /etc/rsyslog.d/"{{ component }}".conf

- name: Start rsyslog service
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
