- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Create a common secrets file
      ansible.builtin.lineinfile: #Need to modify secrets directory
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/common token={{vault_token}} url=https://vault.vdevops.cloud:8200 validate_certs=False') }}"
        create: yes

    - name: Create a common secrets file
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.vdevops.cloud:8200 validate_certs=False') }}"
        create: yes