- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Install ansible hvac
      ansible.builtin.shell: sudo pip3.11 install ansible hvac -y

    - name: Create a common secrets file
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        content: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.vdevops.cloud:8200 validate_certs=False') }}"
        create: yes

    - name: Create a common secrets file
      ansible.builtin.lineinfile:
        path: ~/app.json
        content: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.vdevops.cloud:8200 validate_certs=False') }}"
        create: yes