- name: MYSQL Setup
  hosts: all
  become: yes
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start MySQL server
      ansible.builtin.systemd.service:
          name: mysqld
          state: started

    - name: Setup MySQL password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

